### PR TITLE
Fix Monaco accessing navigator and breaking SSR

### PR DESCRIPTION
**Pull request by davedbase**

### CODE REVIEW

**Comment by amoutonbrady** [comment]
Quick questions:
- Wouldn't it be easier to apply that `<Show when={!isServer} />` directly from userland rather than here?
- Have you had a chance to confirm that this resolve your use case?

Other than that, this PR sounds fine to me :)

**Comment by davedbase** [comment]
```Wouldn't it be easier to apply that <Show when={!isServer} /> directly from userland rather than here?```

This came up because I started porting solid-site to solid-start. Monaco completely barfs because it accesses navigator. There's 4-5 places that it happens I figured it might be easier and more direct to do it right in the package? Since SSR will *never* be supported I personally think it makes sense.

```Have you had a chance to confirm that this resolve your use case?```

Nope, but if this doesn't correct it I'm not sure what else we can reasonably do. If Monaco is calling navigator and tripping up the SSR process that's a pretty big blocker that will need deeper investigation. At least blocking it from rendering is a start though? I might be wrong :-)

**Comment by amoutonbrady** [comment]
Sounds fair, will merge :)

**Comment by modderme123** [comment]
It might also make sense to not render MonacoTabs either and keep all monaco imports off the server

**Comment by amoutonbrady** [comment]
@davedbase I'll need a little bit more time to get this over with. @modderme123 suggestion is actually on point and I need to investigate this a tat bit more.

**Pull request merged**
