### PR TITLE
Include ref prop on Repl Component

### PR DESCRIPTION
**Pull request by aquaductape**
Include ref prop on Repl Component.

Example:
```js
let replEl!: HTMLDivElement;

return (
    <Repl
      compiler={compiler}
      formatter={formatter}
      isHorizontal={true}
      interactive={true}
      actionBar={true}
      editableTabs={true}
      dark={false}
      //...
      ref={replEl}
    />
);
```

### CODE REVIEW

**Comment by modderme123** [comment]
Two notes: you shouldn't need `| undefined` and you should copy the types to types/types.d.ts. Also, I'm curious... What is the use of getting the div at the root of the repl?

**Comment by aquaductape** [comment]
I need it in order to style the root of the repl.

Maybe adding a class prop is better for my specific case.

```js
  return (
    <div
      class={`relative grid bg-blueGray-50 h-full overflow-hidden text-blueGray-900 dark:text-blueGray-50 font-sans
 ${props.class}`}
      // ...
    >
```

**Comment by amoutonbrady** [comment]
I'm definitely not against a `class` props. That being said, class or ref, I'm wondering if we shouldn't think this a bit bigger.

I'm mostly thinking naming. Today your need is to add some styling on top of the root element. What if later you need to style some other part of the REPL?

I wonder if we shouldn't come up with named ref/classes like:
```tsx
<Repl rootRef={...} editorRef={} previewRef={} actionRef={} />
```
or
```tsx
<Repl rootClass={...} editorClass={} previewRef={} actionClass={} />
```

@modderme123 any though on that?

**Comment by modderme123** [comment]
The named refs or classes feels like API bloat to me... I wonder if we could instead just break up repl into components and give a class attribute to each of those? Maybe something like this:

```tsx
<Repl class={}>
  <Editor class={} />
  <Preview class={} />
  <Action class={} />
</Repl>
```

I'm in favor of a class prop over a ref prop because it creates a more declarative style. However, this PR also looks good.

**Comment by aquaductape** [comment]
> The named refs or classes feels like API bloat to me... I wonder if we could instead just break up repl into components and give a class attribute to each of those? Maybe something like this:
> 
> ```tsx
> <Repl class={}>
>   <Editor class={} />
>   <Preview class={} />
>   <Action class={} />
> </Repl>
> ```
> 
> I'm in favor of a class prop over a ref prop because it creates a more declarative style. However, this PR also looks good.

I kinda like this, but one nitpicky downside is that by default the end user has to import all those components just render the Repl.

**Comment by amoutonbrady** [comment]
Let's roll with the ref for now and see if the needs I'm describing here shows up at some point.

**Pull request merged**
