### PR TITLE
Scaling feature

### PR DESCRIPTION
**Pull request by aquaductape**
This is related to the recent discussion on discord on how some things on this playground is not ideal for video presentation.

One such thing that this PR addresses is preserving visual space when scaling up the page, and only scaling the important UI that users only care about during video presentation, which is the code (Monaco editor) , and the page result (Result iframe/panel).

Peek 2021-07-28 08-15

Here's a screenshot of current website when zoomed in 150%. As you can see the Header takes up a lot of valuable space. Other smaller UI elements when all added together take up space as well.
Screenshot from 2021-07-27 23-12-06

Here's the alternative zoomed in elements when artificially zoomed in "150%"
Screenshot from 2021-07-27 23-12-03

## What's Added

Zoom button in Header
malloney

## How is scaling done?
It updates Monaco's editor font-size `editor.updateOptions({ fontSize });`. 

For the Result panel, it's done via transform property and width/height.
```css
.container {
  transform: scale(1.2);
  transform-origin: 0 0;
  width: 88.33%;
  height: 88.33%;
}
```

There is a CSS property [`zoom`](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom), but it's experimental, is not supported by Firefox, and I couldn't get it to work on an iframe.

## Dropdown Behavior
The button when selected, opens a dropdown with the zoom settings. The dropdown has a "focusout" behavior where pressing Escape key or clicking/focusing outside of the container will close the dropdown.

Peek 2021-07-28 00-31

When pressing `Ctrl+` or `Ctrl-`, the dropdown opens temporarily (1200ms) for immediate feedback. 
The dropdown becomes the active element and is `focus()`. Previous focused element will regain `focus()` when user presses Escape key or dropdown closes after timeout( as long as dropdown hasn't been interacted with, such as Tabbing or selecting inside it or mouse cursor moves within it)

## Settings
Screenshot from 2021-07-27 23-44-26
There's zoom buttons such as `increase`, `decrease`, and `reset`. 

If users are not happy how the default page scaling shortcuts were overriden, there's an option to disable that.

If the user is only interested in scaling Monaco's text, you can disable scaling the Result iframe.

Result iframe is scaled
Screenshot from 2021-07-27 23-43-30
Result iframe is not scaled
Screenshot from 2021-07-27 23-43-43

### CODE REVIEW

**Comment by aquaductape** [comment]
Something I've been debating. Have an option to disable the alternative zoom altogether and when selected will reset to default scale of "100%" and the zoom inputs will be disabled.

Screenshot from 2021-07-28 06-33-16

**Comment by amoutonbrady** [comment]
Hey sorry, that took me a little bit of time to get back to you but man that looks awesome! This surely will be of a lot of help for Ryan when he does his demo and anyone using the playground for showcase on a screen share.

Browser zoom is totally fine as a naming to me. The way you setup the option as is is also completely fine to me.
Overriding by default might not be the best in term of accessibility, but it's probably not the worst either.

Would you consider this feature finished on your end?

PS: Awesome PR description!

**Comment by aquaductape** [comment]
So you're okay with the first option, "Override browser zoom keyboard shortcut".

I agree that override by default is not the best in terms of accessibility, but users wouldn't know about this useful "optimal" zoom. That's why I made sure when you zoom, the dropdown includes the disable option, in case they don't want that. Originally I was going to hide it under  "Advance Settings" for design minimalism, but I wanted users to see right away they can disable it.

This feature complete on my end.

**Comment by amoutonbrady** [comment]
Wonderful, I'll merge that as is. This is a really clean implementation.

Thank you very much!

**Pull request merged**
