### PR TITLE
✨ much better logging

### LINKED ISSUE #94: Intercept console.count/time/timeEnd
It'd be nice if the playground intercepted console.count/time/timeEnd calls too.

### PR DESCRIPTION
**Pull request by modderme123**
It turns out that there are dev tools that are really easy to embed called [eruda](https://github.com/liriliri/eruda). I discovered the package because repl.it uses it in its beta versions. 

fixes #94, #31, #99

Also pinging @otonashixav who worked on a different solution. WDYT of this?

### CODE REVIEW

**Comment by edemaine** [comment]
Will try this out! But natural question is: does it need to be untracked as well?

**Comment by edemaine** [comment]
This looks very cool! The interactive console object exploration is especially nice to reproduce.

Some quick comments/issues I ran into:
* When too narrow, the scrollbars on the tabs is pretty ugly. I guess growing the size to accommodate the horizontal scrollbar (to avoid the need for vertical scrollbar) would be a good start.
* I worry that the dev tools toggle is a little too subtle. I liked the old hint that there are 2 console messages so you might want to open them. If that's too hard, maybe at least making it a horizontal strip instead of a single button would help. Or maybe just the button needs higher contrast colors in dark mode.
* Dev tools popup seems to disappear when clicking the reload button (left of Result) and when clicking the Elements selector. Maybe both could be avoided?
* It's weird not to see a tree in Elements but I guess that's not a feature?
* Maybe disable Source panel if it doesn't work. (I get `Sorry, unable to fetch source code:(`)

**Comment by modderme123** [comment]
Unfortunately, the reloading is a side effect of the devtools and without entirely forking and rebuilding them, we don't have a lot of control over any of its behavior. However, I believe this commit should fix most of the rest of the issues (I personally like the scrollbars but made them match the dark theme)

**Comment by amoutonbrady** [comment]
That's looking amazing, thank you so much!

**Pull request merged**
